version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    # environment:
    #   DB_HOST: postgres
    #   DB_PORT: 5432
    #   DB_USER: ${POSTGRES_USER}
    #   DB_PASSWORD: ${POSTGRES_PASSWORD}
    #   DB_NAME: ${POSTGRES_DB}

  postgres:
    image: postgres:13
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "5432:5432"
